apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
  - image: wingcloudbot/kblocks-controller
    context: ./packages/@kblocks/controller
    sync:
      infer: ["src/**/*.ts"]
  - image: wingcloudbot/kblocks-worker
    context: ./packages/@kblocks/worker
    sync:
      infer: ["src/**/*.ts"]
  - image: wingcloudbot/kblocks-sink
    context: ./test/sink-server
    sync:
      infer: ["src/**/*.ts"]

deploy:
  helm:
    hooks:
      before:
        - host:
            dir: test/
            command:
              - sh
              - -c
              - |
                export KBLOCKS_WORKER_IMAGE="{{ .Values.workerImage }}"
                export KBLOCKS_CONTROLLER_IMAGE="{{ .Values.controllerImage }}"
                ./build.sh
    releases:
      - name: kblocks-test
        chartPath: ./test/helm
        namespace: kblocks-test
        createNamespace: true
        setValueTemplates:
          workerImage: "{{.IMAGE_FULLY_QUALIFIED_wingcloudbot_kblocks_worker}}"
          controllerImage: "{{.IMAGE_FULLY_QUALIFIED_wingcloudbot_kblocks_controller}}"
          sinkImage: "{{.IMAGE_FULLY_QUALIFIED_wingcloudbot_kblocks_sink}}"
