apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
  - image: wingcloudbot/kblocks-operator
    docker:
      dockerfile: ./packages/@kblocks/operator/Dockerfile
      cacheFrom:
        - wingcloudbot/kblocks-operator:latest
    context: .
    sync:
      infer: ["packages/@kblocks/operator/src/**/*.ts"]
  - image: wingcloudbot/kblocks-worker
    docker:
      dockerfile: ./packages/@kblocks/worker/Dockerfile
      cacheFrom:
        - wingcloudbot/kblocks-worker:latest
    context: .
    sync:
      infer: ["packages/@kblocks/worker/src/**/*.ts"]
  - image: wingcloudbot/kblocks-control
    docker:
      dockerfile: ./packages/@kblocks/control/Dockerfile
      cacheFrom:
        - wingcloudbot/kblocks-control:latest
    context: .
    sync:
      infer: ["packages/@kblocks/control/src/**/*.ts"]
  - image: wingcloudbot/kblocks-testserver
    context: ./test/testserver
    sync:
      infer: ["src/**/*.ts"]

deploy:
  helm:
    hooks:
      before:
        - host:
            dir: test/
            command:
              - sh
              - -c
              - |
                export KBLOCKS_WORKER_IMAGE="{{ .Values.workerImage }}"
                export KBLOCKS_OPERATOR_IMAGE="{{ .Values.operatorImage }}"
                export KBLOCKS_CONTROL_IMAGE="{{ .Values.controlImage }}"
                export KBLOCKS_VERSION="0.0.0"
                ./build.sh
    releases:
      - name: kblocks
        chartPath: ./packages/@kblocks/cli/dist
        namespace: kblocks
        createNamespace: true
        setValues:
          system: kblocks-tests
        setValueTemplates:
          workerImage: "{{.IMAGE_FULLY_QUALIFIED_wingcloudbot_kblocks_worker}}"
          operatorImage: "{{.IMAGE_FULLY_QUALIFIED_wingcloudbot_kblocks_operator}}"
          controlImage: "{{.IMAGE_FULLY_QUALIFIED_wingcloudbot_kblocks_control}}"
          testServerImage: "{{.IMAGE_FULLY_QUALIFIED_wingcloudbot_kblocks_testserver}}"

      - name: kblocks-test
        chartPath: ./test/helm
        namespace: kblocks-test
        createNamespace: true
        setValueTemplates:
          workerImage: "{{.IMAGE_FULLY_QUALIFIED_wingcloudbot_kblocks_worker}}"
          operatorImage: "{{.IMAGE_FULLY_QUALIFIED_wingcloudbot_kblocks_operator}}"
          controlImage: "{{.IMAGE_FULLY_QUALIFIED_wingcloudbot_kblocks_control}}"
          testServerImage: "{{.IMAGE_FULLY_QUALIFIED_wingcloudbot_kblocks_testserver}}"

portForward:
  - resourceType: service
    resourceName: kblocks-test-testserver
    namespace: kblocks-test
    port: 80
    localPort: 8080


