apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
  - image: wingcloudbot/kblocks-operator
    context: ./packages/@kblocks/operator
    sync:
      infer: ["src/**/*.ts"]
  - image: wingcloudbot/kblocks-worker
    context: ./packages/@kblocks/worker
    sync:
      infer: ["src/**/*.ts"]
  - image: wingcloudbot/kblocks-control
    context: ./packages/@kblocks/control
    sync:
      infer: ["src/**/*.ts"]
  - image: wingcloudbot/kblocks-testserver
    context: ./test/testserver
    sync:
      infer: ["src/**/*.ts"]

deploy:
  helm:
    hooks:
      before:
        - host:
            dir: test/
            command:
              - sh
              - -c
              - |
                export KBLOCKS_WORKER_IMAGE="{{ .Values.workerImage }}"
                export KBLOCKS_OPERATOR_IMAGE="{{ .Values.operatorImage }}"
                export KBLOCKS_CONTROL_IMAGE="{{ .Values.controlImage }}"
                ./build.sh
    releases:
      - name: kblocks-test
        chartPath: ./test/helm
        namespace: kblocks-test
        createNamespace: true
        setValueTemplates:
          workerImage: "{{.IMAGE_FULLY_QUALIFIED_wingcloudbot_kblocks_worker}}"
          operatorImage: "{{.IMAGE_FULLY_QUALIFIED_wingcloudbot_kblocks_operator}}"
          controlImage: "{{.IMAGE_FULLY_QUALIFIED_wingcloudbot_kblocks_control}}"
          testServerImage: "{{.IMAGE_FULLY_QUALIFIED_wingcloudbot_kblocks_testserver}}"

portForward:
  - resourceType: service
    resourceName: kblocks-test-testserver
    namespace: kblocks-test
    port: 80
    localPort: 8080


