apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: acme.com/v1
kind: Argo
metadata:
  name: argocd
  namespace: argocd
ingressHost: argo.monadahq.com
---
apiVersion: acme.com/v1
kind: Portal
metadata:
  name: eladb-portal
repo:
  name: eladb-portal
  owner: monadaco
