apiVersion: acme.com/v1
kind: Repository
metadata:
  name: my-repo
name: my-unique-repo
owner: monadaco
files:
  .github/workflows/build.yaml: |-
    name: GitHub Actions Demo
    on: [push]
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - run: echo "Building the service"