[book]
authors = ["Elad Ben-Israel"]
description = "Kblocks is a tool for building and deploying infrastructure as code blocks."
language = "en"
multilingual = false
src = "src"
title = "Kblocks"

[output.html]
git-repository-url = "https://github.com/kblocksio/kblocks"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/kblocksio/kblocks/edit/main/docs/{path}"
site-url = "/kblocks/"
cname = "kblocks.io"
input-404 = "not-found.md"
