name: Build

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "20.11.1"

jobs:

  prepare:
    name: "Prepare Release"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ fromJson(steps.changelog.outputs.data).newVersion }}
      last-version: ${{ fromJson(steps.changelog.outputs.data).lastVersion }}
      changelog: ${{ fromJson(steps.changelog.outputs.data).changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Derive appropriate SHAs for base and head
        id: shas
        uses: nrwl/nx-set-shas@v3

      - name: Changelog Generation
        id: changelog
        env:
          GENERATE_VERSION: ${{ github.event_name != 'push' || github.repository != 'winglang/kblocks' }}
        run: ./scripts/changelog.sh

  publish:
    name: Publish ${{ matrix.package }}
    runs-on: ubuntu-latest
    if: ${{ !cancelled() && github.event_name == 'push' && github.repository == 'winglang/kblocks' && github.ref == 'refs/heads/main' }}
    env:
      KBLOCKS_VERSION: ${{ needs.prepare.outputs.version }}
      KBLOCKS_OPERATOR_IMAGE: wingcloudbot/kblocks-operator:${{ needs.prepare.outputs.version }}
      KBLOCKS_CONTROL_IMAGE: wingcloudbot/kblocks-control:${{ needs.prepare.outputs.version }}
      KBLOCKS_WORKER_IMAGE: wingcloudbot/kblocks-worker:${{ needs.prepare.outputs.version }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    needs:
      - prepare
    strategy:
      matrix:
        package:
          - "@kblocks/api"
          - "@kblocks/block"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install Dependencies
        run: npm ci
  
      - name: Publish ${{ matrix.package }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 7
          timeout_minutes: 5
          command: |
            cd packages/${{ matrix.package }}
            npm run publish

  publish_images:
    name: Publish Image ${{ matrix.image }}
    if: ${{ !cancelled() && github.event_name == 'push' && github.repository == 'winglang/kblocks' && github.ref == 'refs/heads/main' }}
    strategy:
      matrix:
        image: [operator, worker, control]
    needs:
      - prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push ${{ matrix.image }}
        uses: docker/build-push-action@v6
        with:
          context: packages/@kblocks/${{ matrix.image }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: wingcloudbot/kblocks-${{ matrix.image }}:latest,wingcloudbot/kblocks-${{ matrix.image }}:${{ needs.prepare.outputs.version }}
          cache-from: type=registry,ref=wingcloudbot/kblocks-${{ matrix.image }}:latest
          cache-to: type=inline
          build-args: |
            KBLOCKS_OPERATOR_IMAGE=wingcloudbot/kblocks-operator:${{ needs.prepare.outputs.version }}
            KBLOCKS_CONTROL_IMAGE=wingcloudbot/kblocks-control:${{ needs.prepare.outputs.version }}
            KBLOCKS_WORKER_IMAGE=wingcloudbot/kblocks-worker:${{ needs.prepare.outputs.version }}

  cut_release:
    name: Cut Release
    if: ${{ !cancelled() && github.event_name == 'push' && github.repository == 'winglang/kblocks' && github.ref == 'refs/heads/main' }}
    needs:
      - prepare
      - publish
      - publish_images

    runs-on: ubuntu-latest
    steps:
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        if: ${{ needs.prepare.outputs.last-version != needs.prepare.outputs.version }}
        with:
          repo-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          tag: "v${{ needs.prepare.outputs.version }}"

      - name: Write Changelog
        uses: DamianReeves/write-file-action@v1.3
        with:
          path: "CHANGELOG.md"
          contents: ${{ needs.prepare.outputs.changelog }}
          write-mode: overwrite
      - name: Cut Development Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Kblocks ${{ needs.prepare.outputs.version }}"
          tag_name: "v${{ needs.prepare.outputs.version }}"
          body_path: CHANGELOG.md
          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
